[package]
name = "rust-tracer"
version = "0.1.0"
authors = ["ngmysamuel <e0148675@u.nus.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.8"
serde = "0.9.7"
serde_derive = "0.9.7"
